name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MARIADB_PASSWORD: password

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_DATABASE: CSplanGo
          MYSQL_USER: admin
          MYSQL_PASSWORD: ${{ env.MARIADB_PASSWORD }}
        ports:
          - 3306
        options: --health-cmd="mysqladmin -h 127.0.0.1 -P 3306 ping" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v2
      - name: Install Database
        run: mysql -h 127.0.0.1 -P ${{ job.services.mariadb.ports[3306] }} -uadmin -p${MARIADB_PASSWORD} < sql/schema.sql
