name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MARIADB_PASSWORD: password

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: CSplanGo
          MYSQL_USER: admin
          MYSQL_PASSWORD: ${{ env.MARIADB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Database
        run: mysql --protocol tcp -u admin -p${MARIADB_PASSWORD} < sql/schema.sql
