name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup DB
        run: mysql --host 127.0.0.1 --port 3306 -uroot -proot <<< sql/schema.sql
      - name: Build
        run: go build
      - name: Start API
        run: nohup ./CSplan-API &
      - name: Run Tests
        run: go test -v .
